const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'app', 'portal', 'marketing', 'page.js');
let content = fs.readFileSync(filePath, 'utf8');

// Fix duplicate classNames generated by previous patches
content = content.replace(/className="([^"]*)"\s+className="text-slate-900 dark:text-white"/g, 'className="$1 text-slate-900 dark:text-white"');
content = content.replace(/className="([^"]*)"\s+className="text-slate-500 dark:text-slate-400"/g, 'className="$1 text-slate-500 dark:text-slate-400"');
content = content.replace(/className="([^"]*)"\s+className="text-slate-400 dark:text-slate-500"/g, 'className="$1 text-slate-400 dark:text-slate-500"');

fs.writeFileSync(filePath, content, 'utf8');
console.log('Duplicate classNames fixed.');
